Feature/sync greeting and ready
de-id/agents-sdk pull request #101
Opened 2024-12-17 13:27 UTC by voldemortman

2024-12-17 13:50 UTC, benyael15 commented on src/createStreamingManager.ts
> +                    connect();
why connect?

2024-12-17 13:51 UTC, benyael15 reviewed
review with @HaMMeRSI

2024-12-17 14:14 UTC, benyael15 commented on src/createStreamingManager.ts
> +                    connect();
call is connectionCallback
its more clear when connect that at first i tought is the actul connetion api - but its not
it is just a callback and flag

2024-12-18 12:25 UTC, HaMMeRSI requested changes

2024-12-18 12:25 UTC, HaMMeRSI commented on src/createAgentManager.ts
> +                        options.callbacks.onConnectionStateChange?.(state);
whyd you moved it here?

connected is only happens after new chat started

2024-12-18 12:25 UTC, HaMMeRSI commented on src/createAgentManager.ts
> +                    return await initializeStreamAndChat(agentInstance, options, agentsApi, analytics, items.chat, ...(newChat ? [greeting] : []));
aint there a prettier way of doing this?
move this logic to getGreeting()?

2024-12-18 12:25 UTC, HaMMeRSI commented on src/createStreamingManager.ts
> +    connect: () => void) {
onConnect

2024-12-19 10:15 UTC, merged